### ISSUE TITLE
Lots of errors before a test is executed

### ISSUE THREAD

**Issue by christopheblin** [kotlintest/kotlintest#257]
In my project, when I run the tests with gradlew build, I can see that lots of time is dedicated to running the tests.

I only have unit tests (no integration test).

Using gradlew build -d, I can see that lots of errors happened BEFORE the test is executed.

I can also see that all the stacktraces have 

    17:38:14.096 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.discoverProjectConfig(Project.kt:15)
    17:38:14.096 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.<init>(Project.kt:27)
    17:38:14.100 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.<clinit>(Project.kt:8)
    17:38:14.100 [DEBUG] [TestEventLogger]          at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)

Is it possible to configure kotlintest so that this discoverProjectConfig does not take 30 seconds ?

Here is an extract of the errors (I have 15K+ lines of errors like that, I can provide the full logs if needed...)

Thanks for your help,

    17:38:14.078 [DEBUG] [TestEventLogger]     file:/Users/christopheblin/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/20.0/89507701249388e1ed5ddcf8c41f4ce1be7831ef/guava-20.0.jar
    17:38:14.090 [DEBUG] [TestEventLogger]     2018-03-06 17:38:14 <> DEBUG org.reflections.Reflections:257 - could not scan file META-INF/MANIFEST.MF in url file:/Users/christopheblin/.gradle/caches/modules-2/files-2.1/com.auth0/java-jwt/2.2.1/820daba165fd57835f384b12b4b69b233ec3a03a/java-jwt-2.2.1.jar with scanner SubTypesScanner
    17:38:14.095 [DEBUG] [TestEventLogger]     org.reflections.ReflectionsException: could not create class object from file META-INF/MANIFEST.MF
    17:38:14.095 [DEBUG] [TestEventLogger]          at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
    17:38:14.095 [DEBUG] [TestEventLogger]          at org.reflections.Reflections.scan(Reflections.java:253)
    17:38:14.095 [DEBUG] [TestEventLogger]          at org.reflections.Reflections.scan(Reflections.java:202)
    17:38:14.096 [DEBUG] [TestEventLogger]          at org.reflections.Reflections.<init>(Reflections.java:123)
    17:38:14.096 [DEBUG] [TestEventLogger]          at org.reflections.Reflections.<init>(Reflections.java:168)
    17:38:14.096 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.discoverProjectConfig(Project.kt:15)
    17:38:14.096 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.<init>(Project.kt:27)
    17:38:14.100 [DEBUG] [TestEventLogger]          at io.kotlintest.Project.<clinit>(Project.kt:8)
    17:38:14.100 [DEBUG] [TestEventLogger]          at io.kotlintest.KTestJUnitRunner.<init>(KTestJUnitRunner.kt:10)
    17:38:14.100 [DEBUG] [TestEventLogger]          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    17:38:14.101 [DEBUG] [TestEventLogger]          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    17:38:14.101 [DEBUG] [TestEventLogger]          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    17:38:14.101 [DEBUG] [TestEventLogger]          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    17:38:14.101 [DEBUG] [TestEventLogger]          at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
    17:38:14.101 [DEBUG] [TestEventLogger]          at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    17:38:14.102 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
    17:38:14.103 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    17:38:14.103 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    17:38:14.103 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    17:38:14.103 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    17:38:14.103 [DEBUG] [TestEventLogger]          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    17:38:14.103 [DEBUG] [TestEventLogger]          at java.lang.reflect.Method.invoke(Method.java:498)
    17:38:14.104 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    17:38:14.104 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    17:38:14.104 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    17:38:14.104 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    17:38:14.115 [DEBUG] [TestEventLogger]          at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
    17:38:14.116 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    17:38:14.116 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    17:38:14.117 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    17:38:14.117 [DEBUG] [TestEventLogger]          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    17:38:14.117 [DEBUG] [TestEventLogger]          at java.lang.reflect.Method.invoke(Method.java:498)
    17:38:14.117 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    17:38:14.117 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    17:38:14.118 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
    17:38:14.118 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
    17:38:14.118 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    17:38:14.118 [DEBUG] [TestEventLogger]          at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    17:38:14.118 [DEBUG] [TestEventLogger]          at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
    17:38:14.119 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    17:38:14.119 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    17:38:14.119 [DEBUG] [TestEventLogger]          at java.lang.Thread.run(Thread.java:748)
    17:38:14.119 [DEBUG] [TestEventLogger]     Caused by: org.reflections.ReflectionsException: could not create class file from MANIFEST.MF
    17:38:14.121 [DEBUG] [TestEventLogger]          at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
    17:38:14.121 [DEBUG] [TestEventLogger]          at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
    17:38:14.121 [DEBUG] [TestEventLogger]          at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
    17:38:14.121 [DEBUG] [TestEventLogger]          ... 46 more
    17:38:14.122 [DEBUG] [TestEventLogger]     Caused by: java.io.IOException: bad magic number: 4d616e69
    17:38:14.122 [DEBUG] [TestEventLogger]          at javassist.bytecode.ClassFile.read(ClassFile.java:825)
    17:38:14.122 [DEBUG] [TestEventLogger]          at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
    17:38:14.122 [DEBUG] [TestEventLogger]          at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
    17:38:14.122 [DEBUG] [TestEventLogger]          ... 48 more

**Comment by christopheblin** [comment]
I think it is similar to #232 which has not been resolved apparently ...

**Comment by sksamuel** [comment]
This is fixed in 3.0.0 RC1. 
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md

**Comment by christopheblin** [comment]
I've tested with 

    testCompile 'io.kotlintest:kotlintest-core:3.0.0-RC2'
    testCompile 'io.kotlintest:kotlintest-assertions:3.0.0-RC2'
    testCompile 'io.kotlintest:kotlintest-runner-junit5:3.0.0-RC2'

and

    apply plugin: 'org.junit.platform.gradle.plugin'

The tests are run BUT the errors are still printed on the console output and the tests are still slow to being executed (whereas execution of the test is fast, but the startup time is enormous)

Here is an excerpt of my console :

    6:51 <> DEBUG org.reflections.Reflections:257 - could not scan file org/joda/time/tz/data/America/Argentina/Rio_Gallegos in url file:/Users/christopheblin/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.8.1/f5bfc718c95a7b1d3c371bb02a188a4df18361a9/joda-time-2.8.1.jar with scanner SubTypesScanner
    org.reflections.ReflectionsException: could not create class object from file org/joda/time/tz/data/America/Argentina/Rio_Gallegos
    at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
    at org.reflections.Reflections.scan(Reflections.java:253)
    at org.reflections.Reflections.scan(Reflections.java:202)
    at org.reflections.Reflections.<init>(Reflections.java:123)
    at io.kotlintest.runner.junit5.TestDiscovery.reflections(TestDiscovery.kt:21)
    at io.kotlintest.runner.junit5.TestDiscovery.scan(TestDiscovery.kt:28)
    at io.kotlintest.runner.junit5.TestDiscovery.invoke(TestDiscovery.kt:38)
    at io.kotlintest.runner.junit5.KotlinTestEngine.discover(KotlinTestEngine.kt:127)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
    at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    Caused by: org.reflections.ReflectionsException: could not create class file from Rio_Gallegos
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
    at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
    ... 14 more
    Caused by: java.io.IOException: bad magic number: 43000500
    at javassist.bytecode.ClassFile.read(ClassFile.java:825)
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
    ... 16 more
    2018-03-27 14:56:51 <> DEBUG org.reflections.Reflections:257 - could not scan file org/joda/time/tz/data/America/Argentina/Salta in url file:/Users/christopheblin/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.8.1/f5bfc718c95a7b1d3c371bb02a188a4df18361a9/joda-time-2.8.1.jar with scanner SubTypesScanner
    org.reflections.ReflectionsException: could not create class object from file org/joda/time/tz/data/America/Argentina/Salta
    at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
    at org.reflections.Reflections.scan(Reflections.java:253)
    at org.reflections.Reflections.scan(Reflections.java:202)
    at org.reflections.Reflections.<init>(Reflections.java:123)
    at io.kotlintest.runner.junit5.TestDiscovery.reflections(TestDiscovery.kt:21)
    at io.kotlintest.runner.junit5.TestDiscovery.scan(TestDiscovery.kt:28)
    at io.kotlintest.runner.junit5.TestDiscovery.invoke(TestDiscovery.kt:38)
    at io.kotlintest.runner.junit5.KotlinTestEngine.discover(KotlinTestEngine.kt:127)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
    at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    Caused by: org.reflections.ReflectionsException: could not create class file from Salta
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
    at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
    ... 14 more
    Caused by: java.io.IOException: bad magic number: 43000500
    at javassist.bytecode.ClassFile.read(ClassFile.java:825)
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
    at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
    ... 16 more

Please note that I have created a io.kotlintest.provided.ProjectConfig.kt file with the following content :

    package io.kotlintest.provided
    
    import io.kotlintest.AbstractProjectConfig
    
    class ProjectConfig : AbstractProjectConfig() {
    
    }

Ant it seems it is just ignored

The other big problem for me is "Breaking: One instance per test changes" -> I now have all my tests that fail when I am using verify(xxxMock) because a previous test has called the method ...

I can rearrange my tests to be flat but I will do so only if the speed is fixed first (otherwise, I'll switch to another solution)

**Comment by christopheblin** [comment]
Another problem I have with the new version is that the number of tests is badly reported

Something like "128 of 131 tests passed" and I have something like 100 fails ...

**Comment by sksamuel** [comment]
Ok thanks for the feedback.

There (were) two places were the scans happened. The first was to find the config file, which is now no longer the case. And the second is to find the tests to run. The second one is what's causing your issue here as it's scanning your entire classpath, and it seems like there's jars on there which are from an unsupported version of java, hence all the exceptions. 

`Caused by: java.io.IOException: bad magic number: 43000500`

Those exceptions occur when your runtime doesn't understand a newer version of Java. The first thing I'll do is swallow those exceptions as there's no need to report them. And secondly, I'll see if jUnit5 can be more precise on which jars to scan. Expect a fix overnight.

As for your second issue, the wrong number of tests, Where are you getting that message, is that in intellij or gradle?

**Comment by christopheblin** [comment]
This is in IntelliJ

For the moment, it does not compile on the CLI 

    $ ./gradlew build

    FAILURE: Build failed with an exception.

    * Where:
     Build file '/Users/christopheblin/Documents/beasynessbackend/api/build.gradle' line: 13

    * What went wrong:
    A problem occurred evaluating root project 'api'.
    > Plugin with id 'org.junit.platform.gradle.plugin' not found.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 2.293 secs

This might be the cause of other problems, do you have any hints/tips/advices ?

**Comment by sksamuel** [comment]
That's to allow gradle to use junit platform based test frameworks (like KotlinTest 3). So it's the same for Spek 2 and Junit 5 etc. Gradle themselves say they've built in support in 4.6 but I find the tests just hang if you don't include it, so must be a bug and maybe 4.7 will fix it.

Anyway, sounds like you missed 
```
dependencies {
 classpath "org.junit.platform:junit-platform-gradle-plugin:1.1.0"
}
```
which must be part of your 
```
buildscript {

}
```
section

**Comment by christopheblin** [comment]
Ok I've done that and now it compiles and run the tests

The problem is that the errors I reported to you are now printed in the CLI so I cannot really tell you if the problem on the number of reported tests occur ... 

Please update this issue when you release the 3.0.0-rc3, I'll test again

**Comment by sksamuel** [comment]
Yeah the error with the scan will happen in all places.
