### ISSUE TITLE
Test Events Not Received After Running Tests

### ISSUE THREAD

**Issue by napperley** [kotlintest/kotlintest#316]
Every time tests are executed via the **test** Gradle task in IntelliJ the **Run** window displays the following message (towards the left side): ```Test events were not received```. There is terminal output on the tests however there is no visual output/input.

![test events not received in intellij](https://user-images.githubusercontent.com/3538279/39498653-746c8406-4dfd-11e8-8354-7cfea5e855e4.png)

Using the following software:

- IntelliJ 2018.2
- Kotlin 1.2.41
- Kotlin Test 3.0.6
- Gradle 4.7 (using official Kotlin DSL)
- Zulu JDK 10.0.0 (via SDK Man)
- Ubuntu 16.04

**Comment by elect86** [comment]
Same, downgraded to 3.0.5 worked for me

**Comment by napperley** [comment]
Tried Kotlin Test 3.0.5 but the issue still occurs.

**Comment by sksamuel** [comment]
I think this is probably fixed in 3.1.x without actually checking (lol). I'll take a look tomorrow. But in the meantime, how are you running "the test task in gradle" in intellij so I know I'm doing the same thing ?

**Comment by napperley** [comment]
@sksamuel - I'm going to assume you are using Kotlin 1.2.41, Gradle 4.7 (via Kotlin DSL), and IntelliJ 2018.2. In IntelliJ a Gradle run configuration is created with the **Tasks** field set to test, and the **Gradle project** field set to the current project.

Note that IntelliJ (v2018 and greater) can now autocomplete any custom tasks that have been defined in a **build.gradle.kts** file.

**Comment by sksamuel** [comment]
I've fixed this in master, and it's included in the 3.1.0-RC3 release I've just deployed.
I might be able to backport it to 3.0.x but that will be next week.

**Comment by sksamuel** [comment]
3.1.0-RC4 is released now. Closing this ticket as I believe it's fixed in RC3 and RC4.

**Comment by sksamuel** [comment]
Let's make sure we're talking about the same thing.

I use kotlintest itself as an example project with tests. Import into intellij.

![1](https://user-images.githubusercontent.com/743706/39968090-5c68129c-56bf-11e8-9fc3-1e61d8916be3.png)

Then open up the run/debug configurations and create a new gradle config, setting task to test or clean test.

![2](https://user-images.githubusercontent.com/743706/39968097-82bca5ca-56bf-11e8-9762-6f111f948925.png)

Run tests. 
![3](https://user-images.githubusercontent.com/743706/39968101-994ee65e-56bf-11e8-9212-93cc78951df6.png)

Results appear in the run output.

![4](https://user-images.githubusercontent.com/743706/39968118-da038d8a-56bf-11e8-9f0d-8788e5412083.png)

**Comment by elect86** [comment]
I cant explain what happened, however I pulled/updated from an another computer the same project ([assimp](https://github.com/kotlin-graphics/assimp)), right click and run and this time worked as a charm

![Imgur](https://i.imgur.com/e3M5GkS.png)

**Comment by elect86** [comment]
Ok, thanks anyway for your time and effort!

**Comment by bjonnh** [comment]
I'm still having this issue with latest IntelliJ EAP 2019.2, kotlintest 3.3.2 and junit-jupiter:5.4.2

**Comment by ghost** [comment]
Same here... still happening.

**Comment by itudoben** [comment]
https://youtrack.jetbrains.com/issue/IDEA-221159

**Comment by Timothyryanhall** [comment]
I configured Intellij to be the test runner, rather than Gradle, and it worked for me. https://www.jetbrains.com/help/idea/work-with-tests-in-gradle.html

**Comment by asarkar** [comment]
@Timothyryanhall yes, but you can't do that for projects that require code generation, like gRPC.

**Comment by sghpjuikit** [comment]
All of a sudden I was facing this problem as well. Latest Intellij, kotlintest, gradle...

`Invalidate Caches / Restart` fixed the issue
