### ISSUE TITLE
Failing tests reported as a success AND a failure

### ISSUE THREAD

**Issue by sazzer** [kotlintest/kotlintest#42]
I've just started using this, so apologies if I'm missing something.

When I write tests that pass, all is good and happy. However, if the tests fails then I get two runs of the test reported, one that passed and one that failed with the actual error. This doesn't actually cause problems - the overall test still failed - but it looks weird.

For example, the test:
```kotlin
class DemoTest : WordSpec() {
    init {
        "calculator" should {
            "perform addition" {
                (1 + 1).shouldEqual(3)
            }
        }
    }
}
```

Gives the following output in Maven:
```
Tests in error:
calculator.should perform addition(calculator)
  Run 1: PASS
  Run 2: 2 did not equal 3
```

Fixing the test so that it passes appears to only run the test once, and that is what I'd expect here too.

**Comment by sksamuel** [comment]
It's something to do with the way intellij lays out the tests when using a junit runner. I hope junit 5 fixes it, and its in alpha now.

**Comment by russel** [comment]
I would hypothesize that the green is shown whilst the test is happening and if it fails the green is supposed to be amended to be red, but instead for this plugin only, a new line is being written instead of the old one overwritten. This doesn't happen for other plugins using the JUnit runner.

**Comment by sksamuel** [comment]
It could be that yes. The way it works in junit is you just tell it the status of a test "description". So for some reason it thinks its there twice. Might be something to do with the equality of the instance. Also there are definitely some bugs here, if you put brackets in your test names it all goes wonky. That's something other frameworks have reported and is fixed in JU5.

**Comment by helmbold** [comment]
Would the TestNG be runner an option?

**Comment by sazzer** [comment]
Whilst this happens in IntelliJ as well, what I'm describing here is actually in a command-line Maven build instead.

**Comment by sksamuel** [comment]
@sazzer I've setup a maven pom and used your demo test, and I get this output:

Tests in error: 
  should perform addition(calculator): 2 did not equal 3


Ie, just the single test. How are you getting the "run 1" "run 2" output, is that some maven plugin?

**Comment by sazzer** [comment]
That was just Surefire. Nothing special at all.

If I get time I'll try and set up a bare-bones project and reproduce it.

**Comment by sksamuel** [comment]
Thanks

**Comment by mfriedenhagen** [comment]
Just to second @sksamuel: I get the same here: Using maven-surefire-plugin:2.19.1 I get a passing and a failing test for e.g. `ShouldSpec` and `BehaviorSpec`.

**Comment by mfriedenhagen** [comment]
With Maven this runs into https://github.com/apache/maven-surefire/blob/surefire-2.19.1/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java#L360

**Comment by mfriedenhagen** [comment]
* I created a little test project https://github.com/mfriedenhagen/kotlintest-surefire including a failing travis build.
* One thing: kotlintest spec tests are reported as errors, not as failures (*failures* are `AssertionError`s every other exception is reported as *error*).

**Comment by mfriedenhagen** [comment]
I added a passing test in `UserTest` and `UserFunTest` and another failing in `UserShouldTest`, all failing (or better erring) tests are counted twice.

**Comment by sksamuel** [comment]
Thanks for taking the time to do this. I can investigate and fix the issue now.

**Comment by mfriedenhagen** [comment]
I think kjunithandler should rethrow AssertionError and the custom TestFailedException would be Vetter called TestErrorException (or just re- thrown with some context information or as RTE)

While we are at it: AssumptionViolatedException should probably be handled as "ignored" test to be consistent with JUnit.

Unfortunately I am not able to build the project (neither master nor 1.2.0) on Mac OS X (jdk7.0.72, gradle 2.14).

**Comment by mfriedenhagen** [comment]
The MacOSX problem is this: https://youtrack.jetbrains.com/issue/KT-5256. `io.kotlintest.matchers.be` and `io.kotlintest.matchers.Be`(note the case) are defined in the same kotlin file.

**Comment by sksamuel** [comment]
That's fixed in release/1.3 (or should be!). Can you try that branch?

**Comment by sksamuel** [comment]
Partial fix in place. Replaced all TestFailedException with assertion errors and now errors are failures.

**Comment by sksamuel** [comment]
Ok so turns out junit docs are wrong. You shouldn't call fireTestFinished if the test fails, even though the docs say do it anyway. So fixed that.

**Comment by mfriedenhagen** [comment]
At least in Intellij this still does not work properly, only the first failing test is reported as failed, a second failing and a successful are marked with a yellow stop sign.

**Comment by sksamuel** [comment]
Are you building from source @mfriedenhagen

**Comment by mfriedenhagen** [comment]
@sksamuel: First of all thanks for your effort to provide `kotlintest`.
 
I have updated my test project at https://github.com/mfriedenhagen/kotlintest-surefire and hopefully made my expectations clearer (I assume the behavior shown by the plain `JUnit` implementation called `JUnitTest` should be the reference), each of the three test classes now has one failing, one erring and one succeeding test (total of 3 failing, 3 erring and 3 succeeding). `kotlintest.version` may be given as property while calling Maven.

My test setup (project name before the colon):

Given I cloned kotlintest and there ran: `git checkout f35d75ff3f04376bd644e04ff55594225bbdb168; gradle -x signArchives install`
And I checked out master of kotlintest-surefire

When I call (in project kotlintest-surefire):  `mvn -B -q -Dkotlintest.version=1.2.0 clean test`
Then I see
* Total summary: `Tests run: 9, Failures: 1, Errors: 5, Skipped: 0` (expectation `Tests run: 9, Failures: 3, Errors: 3, Skipped: 0`)
* `FunSpecTest` and `ShouldSpecTest` class results show `Tests run: 5, Failures: 0, Errors: 2, Skipped: 0` (`JUnitTest`: `Tests run: 3, Failures: 1, Errors: 1, Skipped: 0`)
* `Specs` show failed as well as erring tests as errors, failing and erring tests are counted twice.

When I call (in project kotlintest-surefire): `mvn -B -q -Dkotlintest.version=1.2.1-SNAPSHOT clean test`
Then I see:
* Total summary: `Tests run: 9, Failures: 3, Errors: 0, Skipped: 0` (expectation would be `Tests run: 9, Failures: 3, Errors: 3, Skipped: 0`)
* `FunSpecTest` and `ShouldSpecTest` class results show `Tests run: 3, Failures: 1, Errors: 0, Skipped: 0` (`JUnitTest`: `Tests run: 3, Failures: 1, Errors: 1, Skipped: 0`)
* So `Specs` do not show erring tests at all with Maven

I assume once this is running correctly with Maven it should behave correctly in IntelliJ as well :-)

**Comment by sksamuel** [comment]
The latest version from release/1.3 gives this output in intelliJ:

![should spec](http://imgur.com/dmJzz0tl.png)
![fun spec](http://imgur.com/YvnGFRRl.png)

And in maven:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ShouldSpecTest
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.056 sec <<< FAILURE! - in ShouldSpecTest
should fail(This ShouldSpec)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: true did not equal false

should err(This ShouldSpec)  Time elapsed: 0 sec  <<< ERROR!
java.lang.RuntimeException: ShouldSpec

Running FunSpecTest
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in FunSpecTest
should fail(FunSpecTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: true did not equal false

should err(FunSpecTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.RuntimeException: FunSpec

Running JUnitTest
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE! - in JUnitTest
shouldErr(JUnitTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.RuntimeException: JUnit
	at JUnitTest.shouldErr(JUnitTest.kt:12)

shouldFail(JUnitTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError
	at JUnitTest.shouldFail(JUnitTest.kt:8)


Results :

Failed tests: 
  FunSpecTest>TestBase.shouldEqual:16 true did not equal false
  JUnitTest.shouldFail:8
  true did not equal false
Tests in error: 
  FunSpecTest.should err » Runtime FunSpec
  JUnitTest.shouldErr:12 Runtime JUnit
  ShouldSpec

Tests run: 9, Failures: 3, Errors: 3, Skipped: 0
```

**Comment by sksamuel** [comment]
That version is on maven central snapshots as 1.2.1-SNAPSHOT. I added to your pom:

```xml
    <repositories>
        <repository>
            <id>maven-central-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

and set the version to `<kotlintest.version>1.2.1-SNAPSHOT</kotlintest.version>`

And then it works with the latest changes. If you're happy with this, I'll release 1.3.0 as this is the last issue outstanding in the 1.3.0 branch.

**Comment by mfriedenhagen** [comment]
Hello @sksamuel, I am pretty sure `notifier.fireTestFinished` has to be called for failing builds as well (see e.g. https://github.com/JetBrains/spek/blob/master/spek-core/src/main/kotlin/org/jetbrains/spek/junit/JUnitNotifier.kt or https://github.com/wgroeneveld/jasmine-junit-runner/pull/21/files).
With "IntelliJ IDEA (Community Edition) 2016.2 EAP Build #IC-162.1120.6, built on June 28, 2016" and the current SNAPSHOT from ossrh I got the following:
<img width="296" alt="kotlintest-1 2 1-snapshot-ij-preview" src="https://cloud.githubusercontent.com/assets/125281/16544708/979e1d3c-4110-11e6-9c86-fad728e0852b.png">

So I reenabled calling `fireTestFinished` in my build (from 446070492a5709eedf5548d86ec74c5f83f81298 changing `if (!failed)` to `if (true)`) and now the output in IntelliJ is correct but Surefire shows the wrong numbers and the additional PASS again. I digged deeply into this and the point is, that the failed status is stored in a `ThreadLocal` in Surefire and lateron retrieved (see https://github.com/apache/maven-surefire/blob/surefire-2.19.1/surefire-providers/common-junit4/src/main/java/org/apache/maven/surefire/common/junit4/JUnit4RunListener.java#L140).
kotlintest runs `fireTestStarted` and `fireTestFinished` on the main thread but  `fireTestFailure` on the Executor thread. Yesterday I fiddled around with collecting `Future<Failure>`s and then call  `fireTestFailure` on the main-thread again (did not finish this). Or "started" and "finished" should be called from the executor as well.

After thinking a while about `TestBase.runTest` I am uncertain whether it does behave correctly:
* If you configured say 10 `invocations` and one of them fails you have no further information which invocation failed.
* Coming from Maven I am always thinking from the "XML output perspective" here. `fireTestStarted` and `fireTestFinished` "render" the starting resp. ending element and `fireTestFailure` sets the state.
* I do not see where any build tool would be able to deduct this for multiple invocations let alone doing these in multiple threads.

This is off-topic for this issue: What is the use case for multiple invocations? If you have differing input parameters you definitely want to create multiple notifier "transactions".

**Comment by helmbold** [comment]
Invoking a single test case parallel with multiple threads is used to provoke multi threading issues.

**Comment by mfriedenhagen** [comment]
@helmbold, of course, sorry. I got my `Future` solution working, see PR #55

**Comment by sksamuel** [comment]
I didn't get the same issues you do @mfriedenhagen. I don't know why, it should have failed for me like it did for you, but you could see the output of running the tests in the screenshots. But your patch makes sense, so that's merged and I've released 1.3.0-SNAPSHOT to central.

**Comment by mfriedenhagen** [comment]
@sksamuel, all machines are different, (OS, JDK, IDE version, plugin version in the IDE, other installed plugins etc.) :-). I mostly trust CI-systems and like Docker containers because they eliminate a lot of difference here (but come with a baggage of their own). Thanks for merging my patch.

**Comment by sksamuel** [comment]
So we should be good for 1.3.0 now then
